// The gate card's words (swarm-fixes round 2026-10-05, finding 4): a gate answers its click with one card —
// what it allows, where it stands, its code, the calls it guards and the tests that reach them — and a config
// check is said to be one. Spread into STRINGS in strings.ts like strings-doors.ts. Same rules as the rest of
// the catalog: both registers, a define on every word a reader may not know, defines in plain words (no
// backticks, no markdown, no dotted identifiers, no placeholders).
import type { StringEntry } from './strings.js';

function same(word: string, define?: string): StringEntry {
  return define ? { hud: word, professional: word, define } : { hud: word, professional: word };
}
function one(word: string, pluralKey: string): StringEntry {
  return { hud: word, professional: word, singularOf: pluralKey };
}

export const GATE_STRINGS: Record<string, StringEntry> = {
  // ── the numbers ────────────────────────────────────────────────────────────
  'count.scope.gate': same('for this gate',
    'What the number beside it counts over: one gate, and the calls a request goes through to meet it. A test is counted once, whether it reaches the gate itself or a call in front of it.'),
  'count.unit.configChecks': same('{n} config checks',
    'Checks on how the application was started, such as a setting that must be present or a mode that is refused in production. They run when the application reads its settings, not on any one request, so they are counted apart from the gates.'),
  'count.unit.configChecksOne': one('1 config check', 'count.unit.configChecks'),
  'count.unit.gateSitsOn': same('{n} parts it sits on',
    'The parts of the code this gate stands in front of directly: the functions and requests that run only once it lets them through.'),
  'count.unit.gateSitsOnOne': one('1 part it sits on', 'count.unit.gateSitsOn'),
  'count.unit.gateCalls': same('{n} of {m} calls',
    'The calls to the service that reach this gate on their way, out of every call the graph knows. A call the gate sits on directly and a call that reaches it further down are both counted, each once.'),
  'count.part.gateCallsOwn': same('{n} it guards directly',
    'Calls the gate stands in front of itself: nothing else runs for them until it lets them through.'),
  'count.part.gateCallsUnder': same('{n} that reach it further down',
    'Calls that run other code first and meet the gate on the way, so the gate stands in front of part of what they do.'),
  'count.unit.gatePages': same('{n} pages',
    'Pages drawn on the server that meet this gate before they are shown. A config check is usually met here, because a page reads the settings to draw itself.'),
  'count.unit.gatePagesOne': one('1 page', 'count.unit.gatePages'),

  // ── the card ───────────────────────────────────────────────────────────────
  'gate.card': same('gate', 'One checkpoint, answered: what it allows, where it stands, its code, the calls it guards and the tests that reach them.'),
  'gate.unnamed': same('a check nobody has put in words',
    'Its only name is the code’s own, which the business register does not print. The card still says where it stands and what reaches it.'),
  'gate.open': same('open this gate', 'Opens the gate card: what it allows, where it stands, its code, the calls it guards and the tests that reach them.'),
  'gate.kind.guard': { hud: 'gate', professional: 'check',
    define: 'A checkpoint on who may go on: signed in, owns the thing, within the rate limit. Its words are policy.' },
  'gate.kind.rule': same('rule', 'A shape the data has to match before it is accepted, such as a required field or an allowed value.'),
  'gate.kind.config': same('config check',
    'A check on how the application was started, not on a request: a setting that must be present, or a mode refused in production. It runs when the application reads its settings.'),
  'gate.kind.declared': same('declared in the config', 'Named in the source’s configuration file rather than found in the code: somebody said this is a gate.'),
  'gate.sec.allows': same('What it allows', 'What this checkpoint lets through and what it refuses, in the words somebody wrote for it.'),
  'gate.sec.where': same('Where it stands', 'The calls and pages a request goes through to meet this checkpoint, and the parts it sits on directly.'),
  'gate.sec.code': same('Its code', 'The checkpoint’s own lines, read from the file on this machine.'),
  'gate.sec.calls': same('The calls it guards', 'Each call to the service that meets this checkpoint on its way, nearest first, with where to read its contract and its handler.'),
  'gate.sec.tests': same('The tests that reach it', 'Each test that reaches this checkpoint itself or a call in front of it, once, with how it is known to reach it.'),
  'gate.sec.sitsOn': same('It sits on', 'The parts this checkpoint stands in front of directly.'),
  'gate.says.phrase': same('Lets a request through only when: {words}', 'The requirement the developer wrote beside the check, as written.'),
  'gate.says.rulePhrase': same('The data has to match: {words}', 'The shape the developer named for the data, as written.'),
  'gate.says.none': same('Nobody has written down what this allows.',
    'No sentence was written for this checkpoint, so the card can say where it stands and what reaches it, but not what it means.'),
  'gate.who.biz': same('Ask the team that owns the {project} code to write one sentence about it.',
    'The people who own the code a checkpoint lives in are the ones who can say what it is for.'),
  'gate.who.bizNoProject': same('Ask the team that owns this code to write one sentence about it.',
    'The people who own the code a checkpoint lives in are the ones who can say what it is for.'),
  'gate.who.code': same('Write it as a business line above {ident} in {path}, or name it in the source’s config file.',
    'A sentence in the doc comment above the function, tagged business, becomes the words every view and the business register print for this checkpoint.'),
  'gate.config.sentence': same('Checks how the application was started, not a request. It runs wherever the application reads its settings.',
    'A config check is met by every call and page that reads the settings, so it is listed apart from the gates a screen’s own requests meet.'),
  'gate.reach': same('reached through {calls} and {pages}', 'The calls and the pages a request or a drawing goes through to meet this checkpoint.'),
  'gate.depth.own': same('guards it directly', 'The checkpoint stands in front of this call itself.'),
  'gate.depth.under': same('{n} calls down', 'The call runs other code first; the checkpoint is met this many calls below it.'),
  'gate.depth.underOne': one('1 call down', 'gate.depth.under'),
  'gate.calls.none': same('no call reaches it in this graph',
    'No route the graph knows goes through this checkpoint. It may be met only at start-up, or only by code the graph did not read.'),
  'gate.tests.none': same('no test reaches it',
    'No test in the graph reaches this checkpoint or a call in front of it.'),
  'gate.tests.onGate': same('reaches the check itself', 'The test runs the checkpoint’s own code.'),
  'gate.tests.viaCall': same('through {call}', 'The test reaches a call in front of the checkpoint, and so the checkpoint on the way.'),
  'gate.more': same('{n} more', 'More of these than the card draws; the count beside the heading counts them all.'),
  'gate.floor': same('at least these', 'The walk up to the calls stopped at its limit, so there may be more than are listed.'),
  'gate.loading': same('reading what reaches it…', 'The service is working out the calls and the tests that reach this checkpoint.'),
  'gate.unavailable': same('the service could not say what reaches it', 'The calls and tests could not be read from the service just now; the rest of the card is from the page.'),
  'gate.atStep': same('show it in the journey', 'Selects the action this checkpoint was met in, in the journey on screen.'),


  // ── tiers (gates lane 2026-10-10): who a gate matters to ───────────────────
  'count.unit.gatesBusiness': same('{n} that matter to the business',
    'The checks a business reader cares about: who may act, the state the record and the records around it must be in, that nothing required is missing, and the policies such as a second approver. Each counted once.'),
  'count.unit.gatesBusinessOne': one('1 that matters to the business', 'count.unit.gatesBusiness'),
  'count.unit.gatesTechnical': same('{n} technical checks',
    'Checks on the shape of the data a request carries and on the platform, such as a request coming from this site or a rate limit. Each counted once; with the ones that matter to the business they make up every gate and rule.'),
  'count.unit.gatesTechnicalOne': one('1 technical check', 'count.unit.gatesTechnical'),
  'count.part.tierBusiness': same('{n} about who may act and the state of the records',
    'Checks on who is signed in and what they may do, and on the state the records must be in.'),
  'count.part.tierPolicy': same('{n} policies', 'Checks the organisation keeps as policy, such as a second approver or no bank details kept.'),
  'count.part.classInput': same('{n} on the data a request carries', 'Checks that the data sent matches the shape the service accepts.'),
  'count.part.classPlatform': same('{n} on the platform', 'Checks every web service keeps, such as a request coming from this site, a rate limit or the shape of an identifier.'),
  'count.unit.preconditions': same('{n} things it needs',
    'What must be true before this action goes through: who may act, the state of the record and the records around it, and the policies. Each counted once.'),
  'count.unit.preconditionsOne': one('1 thing it needs', 'count.unit.preconditions'),

  'gate.tier.business': same('business', 'A check a business reader cares about: who may act, or the state the record must be in.'),
  'gate.tier.policy': same('policy', 'A check the organisation keeps as policy, such as a second approver or no bank details kept.'),
  'gate.tier.technical': same('technical', 'A check on the shape of the data or on the platform. Folded away in the business view.'),
  'gate.tier.head': same('Tier', 'Who this check matters to, and why: the kind of check gives it, unless the team set it.'),
  'gate.tierFrom.class': same('tier from the kind of check', 'The tier follows from what the check protects. The team can set another in the source’s configuration file or beside the check.'),
  'gate.tierFrom.config': same('tier set in the configuration file', 'Somebody named this check’s tier in the source’s configuration file, past the one its kind gives.'),
  'gate.tierFrom.annotation': same('tier written beside the check', 'The team wrote this check’s tier in the comment above it in the code.'),
  'gate.class.identity': same('who is signed in', 'The check is about who is acting: somebody signed in, with a session the service knows.'),
  'gate.class.authorisation': same('what they may do', 'The check is about permission: a role, a scope, or owning the thing being changed.'),
  'gate.class.record-state': same('a record must be in a state', 'The check refuses unless a record, or one loaded beside it, is in the state the action needs.'),
  'gate.class.completeness': same('nothing required is missing', 'The check refuses while a required field, document or line is missing.'),
  'gate.class.integrity': same('it keeps the records honest', 'The check guards against a duplicate, a repeat, or one person doing what needs two.'),
  'gate.class.data-protection': same('it protects data', 'The check keeps data the organisation promised not to hold, such as bank details, out.'),
  'gate.class.input': same('the shape of the data sent', 'The check makes the data a request carries match what the service accepts.'),
  'gate.class.platform': same('a platform check', 'A check every web service keeps, such as a request coming from this site or a rate limit.'),
  'gate.class.configuration': same('how the application was started', 'A check on the settings the application was started with, not on a request.'),
  'gate.class.action-gate': same('the action itself', 'Something the code does that the team marked as a check, because it moves the record on. It is drawn as the action, with what it needs.'),
  'gate.kind.precondition': same('precondition',
    'Something that must already be true before an action goes through, read from the code: the record, or one loaded beside it, in a state, or nothing missing. Otherwise the action is refused.'),
  'gate.pre.else': same('Otherwise: {else}', 'What the code does when the precondition does not hold.'),
  'gate.pre.via.guard-clause': same('a check at the start of the action', 'The code compares the record and refuses before anything changes.'),
  'gate.pre.via.blocker-list': same('one of the reasons the action is blocked', 'The code collects every reason the action cannot go on and refuses once if there is any.'),
  'gate.pre.via.transition-table': same('the table of moves the record may make', 'The code looks the move up in a table of the moves allowed and refuses one that is not there.'),

  // ── the business register's list, by tier ─────────────────────────────────
  'gate.group.whoMay': same('Who may', 'The checks on who is acting and what they may do. A sign-in check met several times is one line per kind of person.'),
  'gate.group.record': same('The record must be', 'What must be true of the record, and of the records loaded beside it, before the action goes through.'),
  'gate.group.policy': same('Policy', 'Checks the organisation keeps as policy, such as a second approver or no bank details kept.'),
  'gate.group.technical': same('+ {n} technical checks',
    'Checks on the shape of the data and on the platform. They are folded in the business view; open them to see each one.'),
  'gate.group.technicalOne': one('+ 1 technical check', 'gate.group.technical'),
  'gate.group.byTier': same('by tier', 'The checks grouped by who they matter to: who may act, the state of the records, policy, and the technical checks folded.'),
  'gate.signedIn': same('signed in', 'Somebody is signed in with a session the service knows.'),
  'gate.signedInTimes': same('folded from {n} sign-in checks', 'Several sign-in checks on this part of the journey say the same thing to a business reader, so they are one line here.'),

  // ── precondition sentences (business lens words, code lens forms) ──────────
  'pre.biz.record': same('{record} is {status}', 'The record must be in this state before the action goes through.'),
  'pre.biz.recordNot': same('{record} is not {statuses}', 'The record must not be in any of these states.'),
  'pre.biz.present': same('{record} has {field}', 'The record must have at least one of these before the action goes through.'),
  'pre.biz.flag': same('{record} is {field}', 'The record must have this set before the action goes through.'),
  'pre.record': same('{record}.{field} = {status}', 'The record’s field must hold this value before the action goes through.'),
  'pre.recordNot': same('{record}.{field} not in {statuses}', 'The record’s field must not hold any of these values.'),
  'pre.role': same('{role} role', 'Only somebody holding this role may take the action.'),
  'pre.signedIn': same('signed in as {actor}', 'Somebody of this kind must be signed in.'),
  'pre.or': same('{a} or {b}', 'Either of these will do.'),
  'pre.notChecked': same('{record} is {status} — not checked by the code',
    'The record moves on from this state, but the code that moves it never checks it is in it first. A record in another state would move too.'),
  'handoff.needs': same('{action} — needs: {list}', 'What must be true before this action goes through, read from the code: who may, the state of the records, and the policies.'),

  // ── the journey's list ─────────────────────────────────────────────────────
  'journey.bizGroup.configChecks': same('Config checks',
    'Checks on how the application was started that this screen’s code meets on the way: a setting that must be present, or a mode refused in production. They are not gates on this screen’s requests, so they are listed and counted apart.'),
  'map.prop.gates.config': same('Config checks met on the way',
    'Checks on how the application was started that this screen’s code meets when it reads its settings. They guard no call of this screen in particular, so they are not counted with its gates.'),
};
