// The dependencies pass's words (docs/proposals/dependencies-and-nx.md §2.1, §2.3): packages as
// nodes — third-party packages and workspace libraries — the files that import them and the
// journeys they reach. Spread into STRINGS in strings.ts like strings-map.ts. Same rules as the
// rest of the catalog: both registers, a define on every word a reader may not know, defines in
// plain words (no backticks, no markdown, no dotted identifiers, no placeholders). The code map
// lane (C) adds its viewer words below this block.
import type { StringEntry } from './strings.js';

function same(word: string, define?: string): StringEntry {
  return define ? { hud: word, professional: word, define } : { hud: word, professional: word };
}
function one(word: string, pluralKey: string): StringEntry {
  return { hud: word, professional: word, singularOf: pluralKey };
}

export const DEPS_STRINGS: Record<string, StringEntry> = {
  'surf.kind.package': same('dependency',
    'A package the code is built on: one somebody else publishes, or a library of this workspace that other parts import by name.'),
  'surf.kind.module': same('file',
    'One source file, as the list of packages it imports.'),
  'count.scope.package': same('for this package',
    'What the number beside it counts over: one package as one source imports it, every file of that source that imports it, wherever the file sits.'),
  'count.unit.packages': same('{n} packages',
    'Dependencies the code imports, each counted once per source: packages somebody else publishes and libraries of this workspace imported by name. The runtime’s own modules are not counted.'),
  'count.unit.packagesOne': one('1 package', 'count.unit.packages'),
  'count.part.packagesThirdParty': same('{n} third-party',
    'Packages somebody else publishes, imported by name from a package registry.'),
  'count.part.packagesThirdPartyOne': one('1 third-party', 'count.part.packagesThirdParty'),
  'count.part.packagesWorkspace': same('{n} from this workspace',
    'Libraries that live in this codebase and are imported by a name, the way a published package would be, rather than by a file path.'),
  'count.part.packagesWorkspaceOne': one('1 from this workspace', 'count.part.packagesWorkspace'),
  'count.unit.importers': same('{n} files import it',
    'Source files that import this package, each counted once however many times it names it. Test and story files are not read for this.'),
  'count.unit.importersOne': one('1 file imports it', 'count.unit.importers'),
  'count.unit.journeysReached': same('{n} journeys reach it',
    'Journeys whose path passes through code that uses this package, or through code that calls that code. Shared helpers are listed but not followed further, so this is a floor.'),
  'count.unit.journeysReachedOne': one('1 journey reaches it', 'count.unit.journeysReached'),

  // ── lane C: the code map grouped and filtered by project and tag, packages drawn, the two views ──
  'codemap.group.label': same('Group',
    'Draw the code map in boxes: one per project, or one per value of a tag dimension such as domain or type. Each box holds the cards of its parts; none draws the usual columns by kind.'),
  'codemap.group.none': same('none', 'No boxes: the code map draws its usual columns by kind.'),
  'codemap.group.project': same('project',
    'One box per project of the workspace: an NX project, a package the workspace lists, or the whole source when it declares none.'),
  'codemap.group.noTag': same('no tag',
    'Parts of projects that carry no tag in this dimension. They are kept, in a box of their own, so nothing drops off the map.'),
  'codemap.group.noProject': same('no project',
    'Parts the graph holds outside every project: journeys, screens that are designed but not built, and anything not under a project folder.'),
  'codemap.group.thirdParty': same('third-party packages',
    'Packages somebody else publishes. They belong to no project of this workspace, so they sit in a box of their own.'),
  'codemap.group.parts': same('{n} parts shown',
    'The cards this box draws right now, each part counted once: a folded group counts every part it folds, under each part’s own kind and only the parts of this box’s project. Tests are not cards here and checks are badges on what they guard, so the inspector’s parts of the code, which counts both, is larger. The breakdown splits them by kind and adds up to the number.'),
  'codemap.group.partsOne': one('1 part shown', 'codemap.group.parts'),
  'codemap.group.scope': same('in this box, as filtered',
    'What the number beside it counts over: the parts one box of the grouped code map draws, after the scope, the code map filters and the focus.'),
  'codemap.group.inspect': same('Open in the inspector',
    'Show this box in the inspector: for a project, its tags, what it depends on, what depends on it and its parts by kind; for a tag value, the projects that carry it.'),
  'codemap.lane.files': same('Files', 'Source files, each as the list of packages it imports. Drawn only with show files on.'),
  'codemap.lane.deps': same('Dependencies', 'Packages the code imports: third-party packages and libraries of this workspace imported by name.'),
  'codemap.pkg.hide': same('hide packages',
    'Leave the package cards off the map, with the arrows into them. The status bar tip counts what this hides.'),
  'codemap.pkg.files': same('show files',
    'Draw a card for each source file, as the list of packages it imports. Off by default: there is one per file and they crowd the map.'),
  'codemap.pkg.thirdParty': same('third-party', 'A package somebody else publishes, imported by name from a package registry.'),
  'codemap.pkg.workspace': same('this workspace',
    'A library that lives in this codebase and is imported by a name, the way a published package would be, rather than by a file path.'),
  'codemap.pkg.title': same('Dependency',
    'What this package is, the versions its projects declare, the files that import it and the journeys that reach code using it.'),
  'codemap.pkg.versions': same('Version by project',
    'The version range each declaring package manifest writes for this package, with the project it sits in. Two manifests that disagree both show.'),
  'codemap.pkg.noDecl': same('declared in no package manifest',
    'The code imports this package but no package manifest above the importing file names it. It may come from a parent install, or the manifest is missing it.'),
  'codemap.pkg.resolves': same('the library it is',
    'The project of this workspace the name resolves to: importing the package is importing that project.'),
  'codemap.pkg.external': same('also an outside system',
    'The workspace configuration names this package as an outside system the code talks to, which has a card of its own.'),
  'codemap.pkg.journeys': same('Journeys that reach it',
    'Journeys whose path passes through code that uses this package, or through code that calls that code.'),
  'codemap.pkg.where': same('Where is it included',
    'Show every file that imports this package, grouped by project, with the version each project declares. Everything else is hidden until you go back to the whole map.'),
  'codemap.pkg.keep': same('Keep what depends on it',
    'Filter the code map to the parts that import or use this package, and the package itself, in their groups.'),
  'codemap.filter.title': same('On the code map',
    'Filters that act on the code map only. They narrow what the map draws inside the sources picked above; every other page keeps the whole scope.'),
  'codemap.filter.projects': same('Projects', 'Keep only the parts of the projects ticked here, and the packages they import.'),
  'codemap.filter.dependsOn': same('Depends on',
    'Keep only the parts that import or use one package, and the package itself, with their groups.'),
  'codemap.filter.anyPackage': same('any package', 'No package filter: the map keeps parts whatever they import.'),
  'codemap.filter.clear': same('clear the code map filters', 'Drop every code map filter. The sources picked above stay as they are.'),
  'codemap.filter.active': same('filtered',
    'The code map draws only what its filters keep. The status bar tip counts the parts they leave out; choose this to drop them.'),
  'codemap.view.menu': same('Views',
    'Two ready-made pictures of the code map: an application with the projects it depends on, and every place one package is included from.'),
  'codemap.view.app': same('App and its related',
    'One project and every project it depends on, directly or through another, drawn as one box each, with arrows labelled by the import statements between them. Everything else is hidden.'),
  'codemap.view.package': same('Where is a package included',
    'Every file that imports one package, grouped by project, with the version each project declares. Everything else is hidden.'),
  'codemap.view.appOf': same('App and its related: {name}',
    'The code map shows only this project and the projects it depends on. Choose it to go back to the whole map.'),
  'codemap.view.packageOf': same('Where is {name} included',
    'The code map shows only this package and the files and code that import it. Choose it to go back to the whole map.'),
  'codemap.view.close': same('back to the whole map', 'Leave this view: the code map draws everything in scope again.'),
  'codemap.view.declared': same('declared only',
    'The project settings name this dependency; no import statement in its files shows it.'),
  'codemap.view.failed': same('This view could not be read from the server',
    'The server did not answer for this project or package. The graph may be older than the build that serves it: re-sync the sources.'),
  'codemap.view.loading': same('reading the view', 'The view is being read from the server.'),
  'codemap.view.noApps': same('no projects in scope', 'The sources in scope declare no projects, so there is no application to draw.'),
  'codemap.view.noPackages': same('no packages in scope', 'The sources in scope import no packages the graph recorded.'),
  'codemap.insp.project': same('Project',
    'The workspace project this part belongs to, read from its project settings (an NX project, a workspace package, or the whole source), with the tags it carries.'),
  'codemap.insp.showApp': same('Show app and its related',
    'Draw this project and every project it depends on, one box each, with the import statements between them. Everything else is hidden.'),
  'codemap.insp.dependsOn': same('Depends on', 'The projects this one depends on: its files import theirs, or its settings declare them.'),
  'codemap.insp.dependents': same('Used by', 'The projects that depend on this one.'),
  'codemap.insp.parts': same('Parts by kind', 'The parts of the code the graph holds for this project, split by kind.'),
  'codemap.insp.importers': same('Where it is included',
    'The files that import this package, grouped by project, each with the line of the import and the code in it that uses the package.'),
  'codemap.insp.inBox': same('Projects in this box', 'The projects that carry this tag value, with their type.'),
  'codemap.insp.used': same('uses it', 'Code in this file whose body uses a name the file imports from the package.'),
  'codemap.ptype.application': same('application', 'A project the workspace declares as an application: something a person runs or opens.'),
  'codemap.ptype.library': same('library', 'A project the workspace declares as a library: code other projects use.'),
  'codemap.ptype.e2e': same('end-to-end tests', 'A project that tests another project end to end.'),
  // ── the project picker (lib/multi-pick.js): one searchable list wherever a project, a tag value or a package is picked ──
  'codemap.pick.projects': same('Projects',
    'Keep only the parts of the projects picked here, and the packages they import. Type to find a project by its name, its words or its tags.'),
  'codemap.pick.tags': same('Tags',
    'Keep only the projects that carry one of the tag values picked here, grouped by the dimension the workspace sorts its tags into, such as domain or type.'),
  'codemap.pick.findProject': same('find a project', 'Type part of a project name, its words or one of its tags.'),
  'codemap.pick.findTag': same('find a tag value', 'Type part of a domain, a type or another tag value.'),
  'codemap.pick.findPackage': same('find a package', 'Type part of a package name.'),
  'codemap.pick.countProjects': same('{n} of {m} projects',
    'How many projects the words typed match, out of every project of the sources in scope. Each project counted once.'),
  'codemap.pick.countTags': same('{n} of {m} tag values',
    'How many tag values the words typed match, out of every value the projects in scope carry. Each value counted once per dimension.'),
  'codemap.pick.countPackages': same('{n} of {m} packages',
    'How many packages the words typed match, out of every package the sources in scope import. Each package counted once per source.'),
  'codemap.pick.selectAll': same('select all shown', 'Pick every option the words typed leave in the list. The keyboard way is Command A in the search field.'),
  'codemap.pick.clear': same('clear', 'Drop every pick in this list.'),
  'codemap.pick.remove': same('remove {name}', 'Drop this pick.'),
  'codemap.pick.more': same('+{n}', 'More picks than fit on one line. Choose this to show all of them.'),
  'codemap.pick.fewer': same('show fewer', 'Fold the picks back to the first few.'),
  'codemap.pick.none': same('nothing matches', 'No option in this list matches the words typed. Esc clears them.'),
  'codemap.pick.group.application': same('Applications', 'Projects the workspace declares as applications: something a person runs or opens.'),
  'codemap.pick.group.library': same('Libraries', 'Projects the workspace declares as libraries: code other projects use.'),
  'codemap.pick.group.e2e': same('End-to-end tests', 'Projects that test another project end to end.'),
  'codemap.pick.group.other': same('Other projects', 'Projects whose settings name no type, such as a whole source read as one project.'),
  'codemap.pick.group.workspace': same('From this workspace',
    'Libraries that live in this codebase and are imported by a name, the way a published package would be.'),
  'codemap.pick.group.thirdParty': same('Third-party', 'Packages somebody else publishes, imported by name from a package registry.'),
  'codemap.pick.kind': same('project',
    'A workspace project: an application, a library or a test project, read from its project settings.'),
  'codemap.pick.dest': same('code map, by project',
    'Fast travel opens the code map grouped by project, with this project in view and its inspector open.'),
  'codemap.pick.dropFilter': same('drop this filter',
    'The code map keeps only what this filter lets through. Choose it to drop this one filter; the scope menu holds the rest.'),
  'codemap.pick.moreFilters': same('+{n} filters', 'More code map filters than fit in the toolbar. Choose this to open the scope menu, where all of them are listed.'),
  'codemap.bar.projects': same('Projects',
    'Pick the projects the code map shows, narrowed by kind, or focus on one application and the projects it depends on. The same project filter as the scope menu.'),
  'codemap.bar.projectsN': same('Projects · {n}',
    'How many projects the code map is filtered to. Open this to change the picks, or focus on one application.'),
  'codemap.bar.types': same('Kinds',
    'Narrow the list below to applications, libraries, end-to-end tests or other projects. With none chosen the list shows every kind. The picks you made stay.'),
  'codemap.bar.focus': same('Focus on an application',
    'Draw one application and every project it depends on, in columns from the application rightward, each arrow labelled with how many import statements cross it.'),
  'tip.stats.files': same('files, drawn only with show files',
    'Source files as the lists of packages they import. The code map draws them only when show files is on.'),
  'tip.stats.packages': same('packages hidden', 'Package cards left off the map by hide packages.'),
  'tip.stats.filtered': same('left out by a code map filter or view',
    'Parts a project, tag or depends-on filter, or one of the two views, leaves off the code map.'),
  'map.band.by': same('Band by',
    'What the rows of journeys on the neighbourhood are grouped by: the source each journey comes from, or its domain.'),
  'map.band.source': same('source', 'One band per indexed source, in the order the design answer names them.'),
  'map.band.domain': same('domain',
    'One band per domain: the domain tag of the project a journey belongs to, else the most common domain among the pages its screens are.'),
  'map.band.noDomain': same('no domain', 'Journeys whose flow and screens belong to no project with a domain tag.'),
};
