// The recorded-fixture work provider (docs/proposals/work-items-sync.md §12 P0).
// A WorkProvider whose tracker is a directory of JSON pages — the way
// examples/invoice-app is the e2e fixture; no network, no MSW (ADR 8).
//
// Directory layout (see fixtures/invoice-app, generated by make-invoice-app.mjs):
//   pages.json        { full: [{file}], incremental: { <cursor>: [file, …] } }
//   pages/*.json      { items: WorkItem[], cursor: string|null, deleted?: string[] }
//   schema.json       the discover() result
//   permissions.json  optional: { credential: {read,write,detail?}, default: 'allow'|'deny',
//                                 deny: { <key>: { <action>: reason } }, allow: { … },
//                                 dryRunRefuses: { <key>: { <action>: reason } } }
//   applied.jsonl     appended by apply(): the fixture tracker's own writes
//   served.json       written by pull(): how far along the recorded timeline the tracker is
//
// The recorded pages are a timeline: the tracker's "now" advances as they are
// served. Its current state = every page served so far (chain order, deletes
// applied) + every applied.jsonl write, each bumping `revision`. So hydrate()
// after the full pull returns the full-pull state, not a later page's.
// Like every provider it never touches the cache and never decides policy.
import { readFileSync, existsSync, appendFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  WorkProvider, Capabilities, Session, Schema, PullPage, Cursor, Scope, SourceConfig,
  WorkItem, WorkAction, Intent, ApplyResult, ProviderVerdict, Change,
} from '@farsight/work';

interface PagesManifest { full: { file: string }[]; incremental: Record<string, string[]> }
interface PageFile { items: WorkItem[]; cursor: string | null; deleted?: string[] }
interface PermissionsFile {
  credential?: { read: boolean; write: boolean; detail?: string };
  default?: 'allow' | 'deny';
  deny?: Record<string, Partial<Record<WorkAction, string>>>;
  allow?: Record<string, Partial<Record<WorkAction, string>>>;
  /** preview() refuses these (the tracker's dry run says no) */
  dryRunRefuses?: Record<string, Partial<Record<WorkAction, string>>>;
}
interface AppliedLine { at: string; intent: Intent; revision: string }

export const FIXTURE_CAPABILITIES: Capabilities = {
  comments: { read: true, write: true, format: 'markdown' },
  transitions: 'graph',
  concurrency: 'revision',
  permissionsProbe: 'per-item',
  deletesVisible: true,
  push: 'none',
  dryRun: true,
};

/** The recorded fixture shipped with this package (CI source for every consumer). */
export const INVOICE_APP_FIXTURE = fileURLToPath(new URL('../fixtures/invoice-app', import.meta.url));

const readJson = <T>(p: string): T => JSON.parse(readFileSync(p, 'utf8')) as T;

function dirOf(s: Session): string {
  const d = s.dir;
  if (typeof d !== 'string') throw new Error(`fixture session ${s.sourceId} has no directory`);
  return d;
}

function manifest(dir: string): PagesManifest {
  return readJson<PagesManifest>(join(dir, 'pages.json'));
}

function page(dir: string, file: string): PageFile {
  return readJson<PageFile>(join(dir, 'pages', file));
}

/** Every page file in chain order: full, then incremental by following cursors. */
function chain(dir: string): PageFile[] {
  const m = manifest(dir);
  const out = m.full.map((f) => page(dir, f.file));
  let cursor = out.at(-1)?.cursor ?? null;
  const seen = new Set<string>();
  while (cursor && m.incremental[cursor] && !seen.has(cursor)) {
    seen.add(cursor);
    const pages = m.incremental[cursor]!.map((f) => page(dir, f));
    out.push(...pages);
    cursor = pages.at(-1)?.cursor ?? cursor;
  }
  return out;
}

/** How many chain pages have been served (the tracker's "now"); 0 before any pull. */
function served(dir: string): number {
  const p = join(dir, 'served.json');
  return existsSync(p) ? readJson<{ pages: number }>(p).pages : 0;
}

function serve(dir: string, pages: number): void {
  if (pages > served(dir)) writeFileSync(join(dir, 'served.json'), JSON.stringify({ pages }) + '\n');
}

/** The chain index where the incremental pages for `cursor` start, or null when off the chain. */
function chainOffset(dir: string, cursor: string): number | null {
  const m = manifest(dir);
  let n = m.full.length;
  let c = page(dir, m.full.at(-1)!.file).cursor;
  const seen = new Set<string>();
  while (c && !seen.has(c)) {
    if (c === cursor) return n;
    seen.add(c);
    const files = m.incremental[c];
    if (!files?.length) return null;
    n += files.length;
    c = page(dir, files.at(-1)!).cursor ?? c;
  }
  return null;
}

function applied(dir: string): AppliedLine[] {
  const p = join(dir, 'applied.jsonl');
  if (!existsSync(p)) return [];
  return readFileSync(p, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l) as AppliedLine);
}

/** One applied write, as the fixture tracker performs it. */
function perform(item: WorkItem, line: AppliedLine, people: Map<string, { id: string; name: string }>): WorkItem {
  const { intent, at, revision } = line;
  const p = intent.payload;
  const who = people.get(intent.requestedBy.id) ?? { id: intent.requestedBy.id, name: intent.requestedBy.id };
  const next: WorkItem = structuredClone(item);
  const change = (field: string, from?: string, to?: string): Change => ({ at, by: who, field, ...(from !== undefined ? { from } : {}), ...(to !== undefined ? { to } : {}) });
  switch (intent.action) {
    case 'comment':
      next.comments.push({ id: `applied-${next.comments.length + 1}`, author: who, created: at, body: { format: 'markdown', raw: p.body ?? '', text: p.body ?? '' } });
      break;
    case 'assign': {
      const to = p.assignee ? people.get(p.assignee) ?? { id: p.assignee, name: p.assignee } : undefined;
      next.history.push(change('assignee', item.assignee?.name, to?.name));
      if (to) next.assignee = to; else delete next.assignee;
      break;
    }
    case 'transition': {
      const name = p.toName ?? (p.to === 'done' ? 'Done' : p.to === 'in-progress' ? 'In Progress' : 'To Do');
      next.history.push(change('status', item.state.name, name));
      next.state = { name, category: p.to ?? item.state.category, since: at };
      break;
    }
    case 'label':
      next.labels = [...new Set([...next.labels.filter((l) => !(p.remove ?? []).includes(l)), ...(p.add ?? [])])];
      next.history.push(change('labels', item.labels.join(' '), next.labels.join(' ')));
      break;
    case 'edit':
      for (const [k, v] of Object.entries(p.fields ?? {})) {
        next.history.push(change(k, String(next.fields[k] ?? ''), String(v)));
        next.fields[k] = v;
        if (k === 'title' && typeof v === 'string') next.title = v;
      }
      break;
    case 'link':
      if (p.kind && p.target) next.links.push({ kind: p.kind, target: p.target, native: p.kind });
      break;
    case 'create':
      break;
  }
  next.updated = at;
  next.revision = revision;
  return next;
}

export interface FixtureOptions {
  /** clock for apply(); defaults to Date.now */
  now?: () => Date;
}

export function createFixtureProvider(opts: FixtureOptions = {}): WorkProvider {
  const now = opts.now ?? (() => new Date());

  const peopleOf = (dir: string) => {
    const p = join(dir, 'people.json');
    const list = existsSync(p) ? readJson<{ id: string; name: string }[]>(p) : [];
    return new Map(list.map((x) => [x.id, x]));
  };

  /** the tracker's current record of every item, deletes applied */
  const current = (dir: string): Map<string, WorkItem> => {
    const out = new Map<string, WorkItem>();
    // before any pull the tracker is at its full-pull state
    const upto = Math.max(served(dir), manifest(dir).full.length);
    for (const pg of chain(dir).slice(0, upto)) {
      for (const it of pg.items) out.set(it.id, it);
      for (const d of pg.deleted ?? []) out.delete(d);
    }
    const people = peopleOf(dir);
    for (const line of applied(dir)) {
      const it = out.get(line.intent.item);
      if (it) out.set(it.id, perform(it, line, people));
    }
    return out;
  };

  const withOverlay = (dir: string, items: WorkItem[]): WorkItem[] => {
    const lines = applied(dir);
    if (!lines.length) return items;
    const cur = current(dir);
    return items.map((it) => (lines.some((l) => l.intent.item === it.id) ? cur.get(it.id) ?? it : it));
  };

  const permissions = (dir: string): PermissionsFile => {
    const p = join(dir, 'permissions.json');
    return existsSync(p) ? readJson<PermissionsFile>(p) : {};
  };

  return {
    id: 'fixture',
    capabilities: FIXTURE_CAPABILITIES,

    async connect(cfg: SourceConfig): Promise<Session> {
      if (!cfg.path) throw new Error(`fixture source ${cfg.id} names no path`);
      const dir = resolve(cfg.path);
      if (!existsSync(join(dir, 'pages.json'))) throw new Error(`fixture source ${cfg.id}: no pages.json in ${dir}`);
      const cred = permissions(dir).credential ?? { read: true, write: true };
      return {
        sourceId: cfg.id, provider: 'fixture', endpoint: dir, dir,
        user: { id: 'fixture-user', name: 'Fixture user' },
        credentialScope: cred, apiVersion: 'fixture-1',
      };
    },

    async discover(s: Session): Promise<Schema> {
      return readJson<Schema>(join(dirOf(s), 'schema.json'));
    },

    async *pull(s: Session, cursor: Cursor | null, scope: Scope): AsyncIterable<PullPage> {
      const dir = dirOf(s);
      // a reconcile scan: the known ids the tracker no longer has ride on the last page
      const gone = (pg: PullPage): PullPage => {
        if (!pg.isLast || !scope.reconcile) return pg;
        const cur = current(dir);
        const extra = scope.reconcile.known.filter((id) => !cur.has(id) && !(pg.deleted ?? []).includes(id));
        return extra.length ? { ...pg, deleted: [...(pg.deleted ?? []), ...extra] } : pg;
      };
      const m = manifest(dir);
      if (cursor === null) {
        const files = m.full;
        for (let i = 0; i < files.length; i++) {
          const pg = page(dir, files[i]!.file);
          serve(dir, i + 1);
          yield gone({ items: withOverlay(dir, pg.items), cursor: pg.cursor, isLast: i === files.length - 1, ...(pg.deleted ? { deleted: pg.deleted } : {}) });
        }
        return;
      }
      const files = m.incremental[cursor];
      if (!files?.length) {
        yield gone({ items: [], cursor, isLast: true });
        return;
      }
      const offset = chainOffset(dir, cursor);
      for (let i = 0; i < files.length; i++) {
        const pg = page(dir, files[i]!);
        if (offset !== null) serve(dir, offset + i + 1);
        yield gone({ items: withOverlay(dir, pg.items), cursor: pg.cursor ?? cursor, isLast: i === files.length - 1, ...(pg.deleted ? { deleted: pg.deleted } : {}) });
      }
    },

    async hydrate(s: Session, ids: string[]): Promise<WorkItem[]> {
      const cur = current(dirOf(s));
      return ids.map((id) => cur.get(id)).filter((x): x is WorkItem => !!x);
    },

    async can(s: Session, item: WorkItem, action: WorkAction): Promise<ProviderVerdict> {
      const p = permissions(dirOf(s));
      const denied = p.deny?.[item.key]?.[action];
      if (denied) return { allowed: false, reason: denied };
      const allowed = p.allow?.[item.key]?.[action];
      if (allowed) return { allowed: true, reason: allowed };
      return p.default === 'deny'
        ? { allowed: false, reason: 'the fixture tracker denies by default' }
        : { allowed: true, reason: 'the fixture tracker allows it' };
    },

    async preview(s: Session, intent: Intent): Promise<ApplyResult> {
      const dir = dirOf(s);
      const cur = current(dir).get(intent.item);
      if (!cur) return { ok: false, error: `no item ${intent.item} on the fixture tracker` };
      if (intent.baseRevision !== undefined && intent.baseRevision !== cur.revision) {
        return { ok: false, conflict: true, error: `revision ${intent.baseRevision} is stale; the tracker has ${cur.revision}` };
      }
      const refuse = permissions(dir).dryRunRefuses?.[cur.key]?.[intent.action];
      return refuse ? { ok: false, error: refuse } : { ok: true, revision: cur.revision };
    },

    async apply(s: Session, intent: Intent): Promise<ApplyResult> {
      const dir = dirOf(s);
      const cur = current(dir).get(intent.item);
      if (!cur && intent.action !== 'create') return { ok: false, error: `no item ${intent.item} on the fixture tracker` };
      if (cur && intent.baseRevision !== undefined && intent.baseRevision !== cur.revision) {
        return { ok: false, conflict: true, error: `revision ${intent.baseRevision} is stale; the tracker has ${cur.revision}` };
      }
      const n = applied(dir).filter((l) => l.intent.item === intent.item).length + 1;
      const base = (cur?.revision ?? '0').split('+')[0];
      const line: AppliedLine = { at: now().toISOString(), intent, revision: `${base}+${n}` };
      appendFileSync(join(dir, 'applied.jsonl'), JSON.stringify(line) + '\n');
      const item = current(dir).get(intent.item);
      return { ok: true, revision: line.revision, ...(item ? { item } : {}) };
    },
  };
}

export const fixtureProvider: WorkProvider = createFixtureProvider();
